### PR TITLE
Sinytra Connector compat fix

### PR DESCRIPTION
**Pull request by eehunter**
This replaces the ItemModelsMixin with a DrawContextMixin, which does almost exactly the same thing in practice, but does not conflict with the changes that Minecraft Forge makes to the ItemRenderer class. This prevents graphical issues when using Revelationary with Sinytra Connector. It also updates the fabric.mod.json file to include the mod's license, which prevents an issue with Minecraft Forge refusing to load mods that don't have a license listed in their metadata.

### CODE REVIEW

**Review by DaFuqs — COMMENTED** [review]
I wonder how that one plays with other item renderers, like REIs batched item renderer, but that's something I will have to check real quick.

**Comment by DaFuqs** [comment]
The revanced mixin does not work with REIs custom item renderer. Indead, it shows the original item texture, instead of the item texture cloaked as.
Might be very well true, that other mods use similar mechanisms to render items and they might break, too. Maybe a different mixin for sintra/non-sintra would be the best bet?

**Comment by eehunter** [comment]
I have noticed the same issue since making the pull request. I will attempt to fix the issue and update the pull request accordingly.

**Comment by eehunter** [comment]
Latest commit fixes the aforementioned graphical issue on Fabric. I will need to do more experimenting to find a solution that will work properly on Forge as well.

**Comment by eehunter** [comment]
This last workaround fixes the issue on Forge (in practice, this has been tested) and Fabric (in theory, but I have no clue how it could possibly not work). I am concerned that it may not perform as well as the original version, so that should be looked into before merging this pull request is considered.
Edit: fix typo
Edit: fix another typo

**Comment by eehunter** [comment]
This also might cause a StackOverflowException if a person decides to, for some reason, cloak an item as itself.

**Comment by ghost** [comment]
not to pester but any updates/progress on this fix?

**Comment by eehunter** [comment]
> not to pester but any updates/progress on this fix?

I've fixed the main issue that this pull request had and am now waiting for DaFuqs to review it. In the mean time, you can download and build my fork if you want to use it sooner rather than later.

**Comment by thedeerirty** [comment]
Hate to bother, but could I get a quick rundown on how to do that?

**Comment by thedeerirty** [comment]
[latest.log](https://github.com/DaFuqs/Revelationary/files/14071541/latest.log)

So I'm running only Spectrum, Revelationary , and its (fabric) requirements with connector, and I keep encountering this error. Revelationary boots fine on its own - it only does this when Spectrum's in the mix. Is it related?

**Comment by ghost** [comment]
> > not to pester but any updates/progress on this fix?
> 
> I've fixed the main issue that this pull request had and am now waiting for DaFuqs to review it. In the mean time, you can download and build my fork if you want to use it sooner rather than later.

i've been bashing (ha) my head against this for a bit now and keep running into errors no matter what i try, any chance you could build your fork for ppl to use until this is officially implemented?

**Comment by thedeerirty** [comment]
> > > not to pester but any updates/progress on this fix?
> > 
> > 
> > I've fixed the main issue that this pull request had and am now waiting for DaFuqs to review it. In the mean time, you can download and build my fork if you want to use it sooner rather than later.
> 
> i've been bashing (ha) my head against this for a bit now and keep running into errors no matter what i try, any chance you could build your fork for ppl to use until this is officially implemented?

I've messed with a bit and after some time got it to work. 
Make sure you build this AND the current build on Spectrum's github. The current release of spectrum doesn't have connector support itself.
Hope that helps

edit: if you're having trouble building a fork just download the zip file of the code, unzip it and run command prompt in the folder, and then execute gradlew build. 
You need to SPECIFICALLY have Java 17 installed. No higher or lower. Found that out from trial and error lol. If you install it you may need to uninstall later versions that superseded it (or at least I did) for it to register.

**Comment by ghost** [comment]
> I've messed with a bit and after some time got it to work. Make sure you build this AND the current build on Spectrum's github. The current release of spectrum doesn't have connector support itself. Hope that helps
> 
> edit: if you're having trouble building a fork just download the zip file of the code, unzip it and run command prompt in the folder, and then execute gradlew build. You need to SPECIFICALLY have Java 17 installed. No higher or lower. Found that out from trial and error lol. If you install it you may need to uninstall later versions that superseded it (or at least I did) for it to register.

thanks for the heads-up on the spectrum version
did you manage to get revelationary+spectrum running? how did you handle dependencies (forge vs fabric versions), i keep getting cardinal components errors

**Comment by DaFuqs** [comment]
Sorry to keep you waiting. Life has been kinda busy lately.
Looks perfect to me, thanks a LOT!

**Comment by DaFuqs** [comment]
I will do a public release shortly

**Comment by DaFuqs** [comment]
Released in Revelationary 1.3.7 on both Curseforge and Modrinth ✅

**Comment by eehunter** [comment]
> thanks for the heads-up on the spectrum version did you manage to get revelationary+spectrum running? how did you handle dependencies (forge vs fabric versions), i keep getting cardinal components errors

In my experience, the latest Cardinal Components API jar from Curseforge (or Modrinth) must be added. Sinytra Connector does not load one of the modules correctly from Spectrum's embedded copy.

**Comment by thedeerirty** [comment]
> > thanks for the heads-up on the spectrum version did you manage to get revelationary+spectrum running? how did you handle dependencies (forge vs fabric versions), i keep getting cardinal components errors
> 
> In my experience, the latest Cardinal Components API jar from Curseforge (or Modrinth) must be added. Sinytra Connector does not load one of the modules correctly from Spectrum's embedded copy.

That's rather odd, because I get this issue _only_ when trying to run this on a server, but not on my client.

**Pull request merged**
