### PR TITLE
Initial 1.20.5 port

### PR DESCRIPTION
**Pull request by imreallybadatnames**
While the lazy workaround for the networking situation is a little hacky, I suppose it shall suffice.
Mainly untested, but compiles perfectly fine.

### CODE REVIEW

**Comment by imreallybadatnames** [comment]
The example datapack works OK now.

**Comment by imreallybadatnames** [comment]
extra screenshot:

**Comment by imreallybadatnames** [comment]
https://github.com/DaFuqs/Revelationary/assets/68000899/f6691cde-63ba-41f4-9301-e5363e83d591

**Comment by DaFuqs** [comment]
Confirmed working perfectly with all I tested. The code looks very clean, too. Thank you!
I will have to look into https://github.com/DaFuqs/Revelationary/pull/14/files#diff-04c84d74d61c44cf9b4213ba2a6593ed97c189bb289d661308b1b344f24ddc14R16 later, which I do not fully understand yet

**Pull request merged**
